---
- name: Install and configure Traefik reverse-proxy
  hosts: localhost

#  roles:
#    - role: ansible-traefik-docker
#      traefik_domain: "mydomain.org"
#      traefik_acme_email: "user@mydomain.org"
#      traefik_dashboard_basicauth_users: ["user:$$apr1$$somehash"]
  tasks: 
    - name: Install Docker and Docker Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy traefik
      docker_compose:
        project_src: .
        state: present


    #INFRASTRUCTURE
    - name: Deploy Organizr              #DASHBOARD
      docker_compose:
        project_src: ./docker/organizr/
        state: present

    - name: Deploy Focalboard
      docker_compose:
        project_src: ./docker/focalboard/
        state: present

    

    ####COMMUNICATION
    - name: Deploy Synapse and Matrix Client   #VOIP, GROUP, DMs
      docker_compose:
        project_src: ./docker/synapse/
        state: present
    
    - name: Deploy roundcube          #Email and web client
      docker_compose:
        project_src: ./docker/roundcube/
        state: present
    
    - name: Deploy myBB forum
      docker_compose:
        project_src: ./docker/mybb/
        state: present

    - name: Deploy FreshRSS
      docker_compose:
        project_src: ./docker/freshrss/
        state: present

  ####DEVELOPMENT
    - name: Deploy Gitea
      docker_compose:
        project_src: ./docker/gitea/
        state: present

    - name: Deploy VS Code server
      docker_compose:
        project_src: ./docker/vscode/
        state: present

    - name: Deploy VaultWarden password manager
      docker_compose:
        project_src: ./docker/vaultwarden/
        state: present

    - name: Deploy Draw.io
      docker_compose:
        project_src: ./docker/drawio/
        state: present
    
    - name: Deploy Neko Firefox browser
      docker_compose:
        project_src: ./docker/neko_browser/
        state: present

    - name: Deploy SearxNG
      docker_compose:
        project_src: ./docker/searxng/
        state: present
    
    - name: Deploy TimeTagger
      docker_compose:
        project_src: ./docker/timetagger/
        state: present

#    - name: Deploy OnlyOffice
#      docker_compose:
#        project_src: ./docker/onlyoffice/
#        state: present

  ####FINANCIAL
  #  - name: Deploy SnipeIT
  #    docker_compose:
  #      project_src: ./docker/snipeit/
  #      state: present

