version: "3.8"

services:
  # Wharf - A web UI for Dokku
  wharf:
    image: kyzima-spb/wharf:latest
    container_name: wharf
    restart: unless-stopped
    environment:
      - WHARF_HOST=dokku.brainiac.gg
      - SECRET_KEY=change-this-secret-key-please
    volumes:
      - /home/dokku:/home/dokku:ro
      - /var/lib/dokku:/var/lib/dokku:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      
      # HTTP Router
      - "traefik.http.routers.dokku-http.rule=Host(`dokku.brainiac.gg`)"
      - "traefik.http.routers.dokku-http.entrypoints=http"
      
      # HTTPS Router
      - "traefik.http.routers.dokku-secure.rule=Host(`dokku.brainiac.gg`)"
      - "traefik.http.routers.dokku-secure.entrypoints=https"
      - "traefik.http.routers.dokku-secure.tls=true"
      - "traefik.http.routers.dokku-secure.tls.certresolver=letsencrypt"
      
      # Service definition
      - "traefik.http.services.dokku-service.loadbalancer.server.port=5000"
      - "traefik.http.routers.dokku-http.service=dokku-service"
      - "traefik.http.routers.dokku-secure.service=dokku-service"
      
      # Headers for SSL/proxy
      - "traefik.http.middlewares.dokku-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.dokku-headers.headers.customRequestHeaders.X-Forwarded-Host=dokku.brainiac.gg"
      - "traefik.http.routers.dokku-secure.middlewares=dokku-headers"

networks:
  proxy:
    external: true