version: "3.8"

services:
  # Simple Dokku dashboard
  dokku-dashboard:
    image: nginx:alpine
    container_name: dokku-dashboard
    restart: unless-stopped
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      
      # HTTP Router
      - "traefik.http.routers.dokku-http.rule=Host(`dokku.brainiac.gg`)"
      - "traefik.http.routers.dokku-http.entrypoints=http"
      
      # HTTPS Router
      - "traefik.http.routers.dokku-secure.rule=Host(`dokku.brainiac.gg`)"
      - "traefik.http.routers.dokku-secure.entrypoints=https"
      - "traefik.http.routers.dokku-secure.tls=true"
      - "traefik.http.routers.dokku-secure.tls.certresolver=letsencrypt"
      
      # Service definition
      - "traefik.http.services.dokku-service.loadbalancer.server.port=80"
      - "traefik.http.routers.dokku-http.service=dokku-service"
      - "traefik.http.routers.dokku-secure.service=dokku-service"

networks:
  proxy:
    external: true