# traefik.toml

# Global configuration
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

# Entrypoints
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]  # Add HTTPS entrypoint
    address = ":443"

# API and dashboard configuration
[api]
  insecure = true
  dashboard = true

# Log configuration
[log]
  level = "DEBUG"

# Access log configuration
[accessLog]

# Providers configuration
[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"


# Certificate resolvers
[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"  # Your email address for Let's Encrypt notifications
  storage = "/acme.json"  # Path to the ACME storage file
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"  # The entrypoint to use for HTTP challenge
  [certificatesResolvers.myresolver.acme.httpsChallenge]
    entryPoint = "websecure"  # The entrypoint to use for HTTPS challenge

