---
- name: Incremental Server Backup and Sync
  hosts: all
  become: yes

  vars:
    external_server: "user@example.com"  # Replace with your external server's SSH username and IP address or hostname
    external_backup_path: "/path/to/external/backup/"  # Replace with the path to the backup directory on the external server

  tasks:
    - name: Ensure backup directory exists
      file:
        path: /backup
        state: directory

    - name: Perform incremental backup
      command: "rsync -avz --delete --exclude=/backup /source/directory/ /backup/"

    - name: Sync backup to external server
      command: "rsync -avz --delete /backup/ {{ external_server }}:{{ external_backup_path }}"


#TEST