version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
    - "8098:80"
    volumes:
    - ./storage/logs:/var/www/html/storage/logs
    depends_on:
    - mariadb-snipeit
    - redis-snipeit
    env_file:
    - .env.docker
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.snipeit.rule=Host(`snipeit.system.exposed`)"
    - "traefik.http.routers.snipeit.entrypoints=https"
    - "traefik.http.routers.snipeit.tls=true"
    - "traefik.http.services.snipeit.loadbalancer.server.port=80"
    networks:
    - proxy

  mariadb-snipeit:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - proxy
    ports:
      - "3306:3306"

  redis-snipeit:
    image: redis:6.2.5-buster
    networks:
    - proxy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - proxy


volumes:
  db: {}

networks:
  proxy:
    external: true