version: "3.6"
services:
    organizr:
        container_name: organizr
        hostname: organizr
        image: organizr/organizr:latest
        restart: unless-stopped
        ports:
            - 8081:80
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.focalboard.rule=Host(`system.exposed`)"
            - "traefik.http.routers.focalboard.entrypoints=https"
            - "traefik.http.routers.focalboard.tls=true"
            - "traefik.http.services.focalboard.loadbalancer.server.port=8000"
        volumes:
            - .:/config
        environment:
            - PUID=<uid>
            - PGID=<gid>
            - TZ=<timezone>
        networks:
            - proxy
networks:
  proxy:
    external: true