version: "3"
services:

  online-go:
    build: .
    image: online-go
    container_name: online-go
    ports:
      - "8089:8089"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-online.rule=Host(`go.system.exposed`)"
      - "traefik.http.routers.go-online.entrypoints=https"
      - "traefik.http.routers.go-online.tls=true"
      - "traefik.http.services.go-online.loadbalancer.server.port=8089"  # Route to port 8000 inside the container
      - "traefik.http.routers.go-online.service=go-online"
      - "traefik.http.services.go-online.loadbalancer.server.scheme=http"  # HTTP inside the container

    networks:
      - proxy

networks:
  proxy:
    external: true