---
- name: Install and configure Traefik reverse-proxy
  hosts: localhost

#  roles:
#    - role: ansible-traefik-docker
#      traefik_domain: "mydomain.org"
#      traefik_acme_email: "user@mydomain.org"
#      traefik_dashboard_basicauth_users: ["user:$$apr1$$somehash"]
  tasks: 
    - name: Install Docker and Docker Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Traefik configuration directory
      file:
        path: /opt/traefik-config
        state: directory

    - name: Download traefik.toml file
      get_url:
        url: "https://raw.githubusercontent.com/HACKERMEN-ORG/hackermen-deployables/main/ansible/hackermen/config/traefik.yml"
        dest: "/opt/traefik-config/traefik.yml"

    - name: Deploy traefik
      docker_compose:
        project_src: ./docker/
        state: present
#CHANGE FOCALBOARD DEPLOYMENT TO DOCKER-COMPOSE  -- ^^ Traefik is proper example of deployment
    - name: Set labels dictionary for Focalboard
      set_fact:
        focalboard_labels:
          traefik.enable: "true"
          traefik.http.routers.focalboard.rule: "Host(`board.system.exposed`)"
          traefik.http.routers.traefik.entrypoints: "websecure"

    - name: Deploy Focalboard container
      docker_container:
        name: focalboard
        image: mattermost/focalboard:latest
        restart_policy: always
        ports:
          - "8000:80" # Expose Focalboard on port 8000
        labels: "{{ focalboard_labels }}"