version: "3.8"

services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: excalidraw
    #ports:
   #   - "3000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`whiteboard.system.exposed`)"
      - "traefik.http.routers.excalidraw.entrypoints=https"
      - "traefik.http.routers.excalidraw.tls=true"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=8947"  # Route to port 8000 inside the container
      - "traefik.http.routers.excalidraw.service=excalidraw"
      - "traefik.http.services.excalidraw.loadbalancer.server.scheme=http"  # HTTP inside the container

    networks:
      - proxy

networks:
  proxy:
    external: true
volumes:
  notused: