version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8367:8080'
    volumes:
      - /location/of/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /location/of/extraConfigs:/configs
#      - /location/of/customFiles:/customFiles/
#      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirlingpdf.rule=Host(`pdf.system.exposed`)"
      - "traefik.http.routers.stirlingpdf.entrypoints=https"
      - "traefik.http.routers.stirlingpdf.tls=true"
      - "traefik.http.services.stirlingpdf.loadbalancer.server.port=8080"
    networks:
      - proxy
networks:
  proxy:
    external: true