services:
  traefik:
    image: traefik:v2.1.6
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard-subdomain.overflow.no`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=staging"
      - "traefik.http.routers.dashboard.middlewares=dashboardAuth"
      - "traefik.http.middlewares.dashboardAuth.basicauth.users=user:$$xx$$xx$$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - "traefik.http.routers.httpCatchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.httpCatchall.entrypoints=http"
      - "traefik.http.routers.httpCatchall.middlewares=httpsRedirect"
      - "traefik.http.middlewares.httpsRedirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpsRedirect.redirectscheme.permanent=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/path/to/traefik/traefik.toml:/traefik.toml"
      - "/path/to/traefik/conf.d:/conf.d"
      - "/path/to/traefik/acme.json:/acme.json"
    container_name: traefik

networks:
  traefik:
    external: true