version: '3.8'

services:
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
      - ./db/sqlite:/var/roundcube/db
    ports:
      - 9002:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`mail.system.exposed`)"
      - "traefik.http.routers.roundcube.entrypoints=https"
      - "traefik.http.routers.roundcube.tls=true"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.google.com
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://smtp.gmail.com
    networks:
      - proxy
networks:
  proxy:
    external: true