---
- name: Install and configure Traefik reverse-proxy
  hosts: localhost

#  roles:
#    - role: ansible-traefik-docker
#      traefik_domain: "mydomain.org"
#      traefik_acme_email: "user@mydomain.org"
#      traefik_dashboard_basicauth_users: ["user:$$apr1$$somehash"]
  tasks: 
    - name: Install Docker and Docker Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Traefik configuration directory
      file:
        path: /opt/traefik-config
        state: directory

    - name: Download traefik.toml file
      get_url:
        url: "https://raw.githubusercontent.com/HACKERMEN-ORG/hackermen-deployables/ansible/traefik_ssl/config/traefik.yml"
        dest: "/opt/traefik-config/traefik.yml"

    - name: Deploy traefik
      docker_compose:
        project_src: ./docker/
        state: present

    - name: Ensure Docker service is started
      service:
        name: traefik
        state: started
        enabled: yes