# General

[log]
  level = "WARNING"

# Entrypoints

[entryPoints.http]
  address = ":80"
[entryPoints.https]
  address = ":443"

# Dashboard

[api]
  dashboard = true

# Dynamic configuration providers

[providers.file]
  directory = "/conf.d"
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik"
  exposedByDefault = false

# Certificate resolvers

[certificatesResolvers.le.acme]
  email = "me@domain.org"
  storage = "acme.json"
  [certificatesResolvers.le.acme.tlsChallenge]