version: '3'
services:
  slash:
    image: yourselfhosted/slash:latest
    container_name: slash
    ports:
      - 5231:5231
    volumes:
      - slash:/var/opt/slash
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.slash.rule=Host(`link.system.exposed`)"
      - "traefik.http.routers.slash.entrypoints=https"
      - "traefik.http.routers.slash.tls=true"
      - "traefik.http.services.slash.loadbalancer.server.port=5231"  # Route to port 8000 inside the container
      - "traefik.http.routers.slash.service=slash"
      - "traefik.http.services.slash.loadbalancer.server.scheme=http"  # HTTP inside the container

    networks:
      - proxy

networks:
  proxy:
    external: true
volumes:
  slash: