---
- name: Create Server Backup
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure backup directory exists
      file:
        path: /backup
        state: directory

    - name: Create disk image backup
      command: "dd if=/dev/sda of=/backup/server_backup.img bs=4M"

#Saves a copy of the entire filesystem on the server