version: "2"

services:
  server:
    image: gitea/gitea:1.22.0-rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"  # Expose port 3000 for HTTP
      - "2222:2222"  # Expose port 2222 for SSH
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.system.exposed`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"  # Route to port 3000 inside the container
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.scheme=http"  # HTTP inside the container
      - "traefik.frontend.headers.customFrameOptionsValue=allow-from https://system.exposed"
      - "traefik.frontend.passHostHeader=true"

networks:
  proxy:
    external: true
