version: "3.4"

services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - config:/App/config
      - data:/App/data
      - translations:/App/wwwroot/translations
      - documents:/App/wwwroot/documents
      - images:/App/wwwroot/images
      - temp:/App/wwwroot/temp
      - log:/App/log
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8085:8085
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lubelog.rule=Host(`auto.system.exposed`)"
      - "traefik.http.routers.lubelog.entrypoints=https"
      - "traefik.http.routers.lubelog.tls=true"
      - "traefik.http.services.lubelog.loadbalancer.server.port=8085"  # Route to port 8000 inside the container
      - "traefik.http.routers.lubelog.service=lubelog"
      - "traefik.http.services.lubelog.loadbalancer.server.scheme=http"  # HTTP inside the container

    networks:
      - proxy

networks:
  proxy:
    external: true


volumes:
  config:
  data:
  translations:
  documents:
  images:
  temp:
  log:
  keys:
