version: '3.5'
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    environment:
      PUBLIC_DNS: domain
      ORGANISATION_UNIT: unit
      ORGANISATION: org
      CITY: city
      STATE: state
      COUNTRY_CODE: country
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio.rule=Host(`draw.system.exposed`)"
      - "traefik.http.routers.drawio.entrypoints=https"
      - "traefik.http.routers.drawio.tls=true"
    networks:
      - proxy
networks:
  proxy:
    external: true


#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 5
#      start_period: 10s