version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - /docker/OliveTin:/config # replace host path or volume as needed
    ports:
      - "1337:1337"
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olivetin.rule=Host(`cmd.system.exposed`)"
      - "traefik.http.routers.olivetin.entrypoints=https"
      - "traefik.http.routers.olivetin.tls=true"
      - "traefik.http.services.olivetin.loadbalancer.server.port=1337"  # Route to port 8000 inside the container
      - "traefik.http.routers.olivetin.service=olivetin"
      - "traefik.http.services.olivetin.loadbalancer.server.scheme=http"  # HTTP inside the container

    networks:
      - proxy

networks:
  proxy:
    external: true

