services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /path/to/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 6000:6000
      - 6001:6001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webtop.rule=Host(`desktop.system.exposed`)"
      - "traefik.http.routers.webtop.entrypoints=https"
      - "traefik.http.routers.webtop.tls=true"
      - "traefik.http.services.webtop.loadbalancer.server.port=6001"  # Route to port 8000 inside the container
      - "traefik.http.routers.webtop.service=webtop"
      - "traefik.http.services.webtop.loadbalancer.server.scheme=http"  # HTTP inside the container

    networks:
      - proxy

networks:
  proxy:
    external: true



    ####https://docs.linuxserver.io/images/docker-webtop/?ref=selfh.st#docker-cli-click-here-for-more-info